name: Deploy to GitHub Pages
on:
  push:
    branches:
      -master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy
        uses: peaceirs/gh-pages@v3
        with:
          github_token: $
{{ secerts.GITHUB_TOKEN }}
          publish_dir: ./
